version: '3.8'

services:
  app:
    build: ./app
    container_name: blog_app
    ports:
      - "5000:5000"
    expose:
      - "5000"
    networks:
      - blog_network

  nginx:
    build: ./nginx
    container_name: blog_nginx
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - blog_network

  jenkins:
    build: ./jenkins
    container_name: blog_jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - blog_network
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  blog_network:
    driver: bridge

volumes:
  jenkins_home:
